Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: stroage/log
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: toor333666
  Host: mysql:3309
  DBName: blog_service
  TablePrefidx: blog_
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30